var DATA = [
        {
            "Id": "1",
            "Br": "RangDong",
            "Cl": "Led Bulbs",
            "Name": " Led Bulb 5W Rang Dong",
            "Price": "1.75",
            "I1": "rd-01",
            "I2": "rd-02",
            "I3": "rd-03",
            "V": "170-250",
            "W": "5",
            "Dc": "LED Bulb 5W Rang Dong fully inherits the most advanced features such as energy saving, long-term use, safety for the health of users. Come to Bright World to own international quality LED bulbs.",
            "Cm1": "Very quality products, fast delivery, good service, will continue to support for a long time.",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "This product is not good",
            "Rate": "3"
        },
        {
            "Id": "2",
            "Br": "RangDong",
            "Cl": "Led Bulbs",
            "Name": " Led Bulb 40W Rang Dong",
            "Price": "9.5",
            "I1": "rd-04",
            "I2": "rd-05",
            "I3": "rd-06",
            "V": "220",
            "W": "40",
            "Dc": "LED Bulb 40W is a high-end product line from Rang Dong brand - a brand that is too familiar to Vietnamese consumers. LED bulbs are integrated production with the most advanced technology today, so this is considered a high-class standard product line according to international standards.",
            "Cm1": "Shop carefully packed, good light, satisfied with the product",
            "Cm2": "Super fast and professional delivery. Genuine and very bright ball, good to use.",
            "Cm3": "Very professional shop, reasonable prices. Fast and guaranteed delivery.",
            "Rate": "5"
        },
        {
            "Id": "3",
            "Br": "RangDong",
            "Cl": "Led Bulbs",
            "Name": " Led Bulb 15W Rang Dong",
            "Price": "3.8",
            "I1": "rd-07",
            "I2": "rd-08",
            "I3": "rd-09",
            "V": "220",
            "W": "15",
            "Dc": "The LED Bulb 15W Rang Dong is applied with modern Led chip technology for a stable, sharp, pleasant and safe light source for the user's vision. LED bulbs are currently very cheap in the lighting market.",
            "Cm1": " Good light bulb, reasonable price",
            "Cm2": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm3": "Good product, well packaged, will buy again in the future",
            "Rate": "4"
        },
        {
            "Id": "4",
            "Br": "Philips",
            "Cl": "Led Bulbs",
            "Name": " Led Bulb 7.5W Philips",
            "Price": "2.6",
            "I1": "pl-01",
            "I2": "pl-02",
            "V": "220-240",
            "W": "7.5",
            "Dc": "Products for natural light effects of 6500K white, 3000K yellow help save electricity up to 85% compared to other light bulbs, which is a safe and environmentally friendly lighting solution.",
            "Cm1": "Good quality, fast delivery, easy to use",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm3": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Rate": "4"
        },
        {
            "Id": "5",
            "Br": "Philips",
            "Cl": "Led Bulbs",
            "Name": "Led Bulb MyCare Philips",
            "Price": "4.2",
            "I1": "pl-03",
            "I2": "pl-04",
            "V": "220-240",
            "W": "8",
            "Dc": "MyCare 8W APR Philips led light bulb is an energy-saving product with full features, demonstrating the best power-saving technology available today. And LED bulbs are a more economical, sustainable and safer lighting solution for your family's health.",
            "Cm1": "This product is not good",
            "Cm2": "Shop carefully packed, good light, satisfied with the product",
            "Cm3": "Super fast and professional delivery. Genuine and very bright ball, good to use.",
            "Rate": "3"
        },
        {
            "Id": "6",
            "Br": "Philips",
            "Cl": "Led Bulbs",
            "Name": "Leb Bulb Philips TForce Core 40W",
            "Price": "10.2",
            "I1": "pl-05",
            "I2": "pl-06",
            "V": "220-240",
            "W": "8",
            "Dc": "Today we would like to introduce a new Philips product that is the TForce Core 40W Philips led light. With many outstanding advantages, this product has been really conquering consumers with the most modern features, bringing the best lighting experience to every space.",
            "Cm1": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm2": "Good light bulb, reasonable price",
            "Cm3": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Rate": "4"
        },
        {
            "Id": "7",
            "Br": "Panasonic",
            "Cl": "Led Bulbs",
            "Name": "Led Bulb 20W Panasonic",
            "Price": "5.8",
            "I1": "pa-01",
            "V": "220",
            "W": "20",
            "Dc": "With an outstanding cylindrical design, Panasonic 20W Led bulbs are manufactured according to Japanese technology with high-quality materials, quality light with 3 main bright colors white, yellow, neutral to ensure a durable lighting system. long. long, save electricity in the system using electricity.",
            "Cm1": "Good product, well packaged, will buy again in the future",
            "Cm2": "Good quality, fast delivery, easy to use",
            "Cm3": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Rate": "5"
        },
        {
            "Id": "8",
            "Br": "Panasonic",
            "Cl": "Led Bulbs",
            "Name": "Led Bulb 8W Panasonic",
            "Price": "7.7",
            "I1": "pa-02",
            "I2": "pa-03",
            "V": "220",
            "W": "8",
            "Dc": "Panasonic 8W LED bulbs are manufactured by famous Panasonic company with more than 100 years of reputation. The company's products are exported to many different countries and received positive feedback from consumers.",
            "Cm1": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm2": "This product is not good",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "4"
        },
        {
            "Id": "9",
            "Br": "Panasonic",
            "Cl": "Led Bulbs",
            "Name": "Led Bulb 6.5W Panasonic",
            "Price": "6.7",
            "I1": "pa-04",
            "V": "220",
            "W": "6.5",
            "Dc": "Panasonic is a manufacturer of electrical and electronic equipment from the land of cherry blossoms - Japan with the most guaranteed quality products that are certified by experts in the world. The company has more than a hundred years of experience, so its product production experience is very high, its products are exported to many countries around the world",
            "Cm1": "Super fast and professional delivery. Genuine and very bright ball, good to use.",
            "Cm2": "Very professional shop, reasonable prices. Fast and guaranteed delivery.",
            "Cm3": "Good light bulb, reasonable price",
            "Rate": "4"
        },
        {
            "Id": "10",
            "Br": "Comet",
            "Cl": "Led Bulbs",
            "Name": "Led Bulb 7W Comet",
            "Price": "1.3",
            "I1": "co-01",
            "I2": "co-02",
            "V": "100-265",
            "W": "7",
            "Dc": "Today, the light bulb is one of the most common electrical and electronic devices in the daily life of world consumers in general and Vietnamese consumers in particular because of its usefulness. Manufacturers of electrical and electronic equipment are also constantly releasing modern light bulbs to meet consumer needs, including the famous Comet brand.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "4"
        },
        {
            "Id": "11",
            "Br": "Comet",
            "Cl": "Led Bulbs",
            "Name": "Led Bulb Rebel 30W Comet",
            "Price": "4.4",
            "I1": "co-03",
            "I2": "co-04",
            "V": "100-265",
            "W": "30",
            "Dc": "As technology becomes more and more modern, more and more electrical products are produced and launched into the market to be able to meet the increasingly diverse needs of people. Today, we would like to introduce to you one of the most popular led bulbs on the market today, which is the Rebel 30W Comet Led bulb.",
            "Cm1": "Very quality products, fast delivery, good service, will continue to support for a long time.",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "This product is not good",
            "Rate": "3"
        },
        {
            "Id": "12",
            "Br": "Comet",
            "Cl": "Led Bulbs",
            "Name": "Led Bulb 12W Comet",
            "Price": "1.8",
            "I1": "co-06",
            "I2": "co-05",
            "V": "100-265",
            "W": "12",
            "Dc": "12W LED bulb Comet is a product of Comet electrical and electronic equipment manufacturer with reputation and many years of experience in the industry, the product always brings quality to satisfy customers.",
            "Cm1": "Shop carefully packed, good light, satisfied with the product",
            "Cm2": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm3": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Rate": "5"
        },
        {
            "Id": "13",
            "Br": "Paragon",
            "Cl": "Led Bulbs",
            "Name": "Led Bulb 13W E27 Paragon",
            "Price": "4",
            "I1": "pr-01",
            "I2": "pr-02",
            "V": "100-240",
            "W": "13",
            "Dc": "Led bulb 13W Paragon is a high-end product line from the experienced Paragon manufacturer in manufacturing and distributing electrical products. Thanks to the full assurance of production standards, the product possesses all the elements of a high-class electrical equipment today.",
            "Cm1": "Good light bulb, reasonable price",
            "Cm2": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm3": "Good product, well packaged, will buy again in the future",
            "Rate": "4"
        },
        {
            "Id": "14",
            "Br": "Paragon",
            "Cl": "Led Bulbs",
            "Name": "Led Bulb 30W E27 Paragon",
            "Price": "13.8",
            "I1": "pr-03",
            "V": "100-240",
            "W": "30",
            "Dc": "The installation meets the standards is an important factor, but there is one more factor that needs to be kept in mind that is the selection of lights to ensure the quality as planned, save operating costs, save money. time. The Paragon 30W LED bulb under the Paragon brand brings together the outstanding advantages of lighting equipment. ",
            "Cm1": "Good quality, fast delivery, easy to use",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm3": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Rate": "4"
        },
        {
            "Id": "15",
            "Br": "Paragon",
            "Cl": "Led Bulbs",
            "Name": "Led Bulb 20W E27 Paragon",
            "Price": "10.4",
            "I1": "pr-04",
            "V": "100-240",
            "W": "20",
            "Dc": "The 20W Paragon led bulb has the standard quality of a high-end lamp but is affordable, so it is preferred by many customers. In addition, this device is also trusted for its outstanding advantages that not all lamps have.",
            "Cm1": "This product is not good",
            "Cm2": "Shop carefully packed, good light, satisfied with the product",
            "Cm3": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Rate": "3"
        },
        {
            "Id": "16",
            "Br": "RangDong",
            "Cl": "Led Tube",
            "Name": " Led Tube Light T8 120/20W E Rang Dong",
            "Price": "9.5",
            "I1": "rd-10",
            "I2": "rd-11",
            "V": "100-250",
            "W": "20",
            "Dc": "With LED Tube T8 120/20W E Rang Dong rotating lamp head, Rang Dong brand once again proved to the whole market the level of a famous lighting brand with many years of experience.",
            "Cm1": "Very professional shop, reasonable prices. Fast and guaranteed delivery.",
            "Cm2": "Good light bulb, reasonable price",
            "Cm3": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Rate": "5"
        },
        {
            "Id": "17",
            "Br": "RangDong",
            "Cl": "Led Tube",
            "Name": " Led Tube Light T8 120/18W (S) Rang Dong",
            "Price": "3.6",
            "I1": "rd-12",
            "I2": "rd-13",
            "V": "170-250",
            "W": "18",
            "Dc": "Currently, Rang Dong lighting brand has become familiar to Vietnamese consumers in particular and the world in general. Advanced lighting products with wide application and high efficiency have been launched by this brand to please its \"gods\". In particular, it is impossible not to mention the LED Tube T8 TT01 120/18W (S)",
            "Cm1": "Good product, well packaged, will buy again in the future",
            "Cm2": "Good quality, fast delivery, easy to use",
            "Cm3": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Rate": "4"
        },
        {
            "Id": "18",
            "Br": "RangDong",
            "Cl": "Led Tube",
            "Name": " Led Tube Light T8 60/10W (S) Rang Dong",
            "Price": "3.8",
            "I1": "rd-14",
            "I2": "ra-15",
            "V": "100-250",
            "W": "10",
            "Dc": "Although there are not many aggressive advertising campaigns, the LED Tube light T8 N01 60/10W (S) Rang Dong is still strong enough to be able to conquer consumers with its own outstanding advantages. . Right from the time it was introduced to the market, this product has dominated the market with its fast-paced consumption.",
            "Cm1": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm2": "This product is not good",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "3"
        },
        {
            "Id": "19",
            "Br": "Philips",
            "Cl": "Led Tube",
            "Name": "Led Tube Light MAS 600mm Philips",
            "Price": "7.8",
            "I1": "pl-07",
            "V": "220",
            "W": "8",
            "Dc": "MAS LEDtube 600mm 8W Philips LED tube light is a product that is widely sold at dealers and stores specializing in electrical products. MAS LEDtube 600mm HO 8W865 T8 Philips LED tube light is one of the most popular products on the market.",
            "Cm1": "Super fast and professional delivery. Genuine and very bright ball, good to use.",
            "Cm2": "Very professional shop, reasonable prices. Fast and guaranteed delivery.",
            "Cm3": "Good light bulb, reasonable price",
            "Rate": "5"
        },
        {
            "Id": "20",
            "Br": "Philips",
            "Cl": "Led Tube",
            "Name": "Led Tube Light Ecofit 20W T8 1m2 Philips",
            "Price": "3.5",
            "I1": "pl-08",
            "V": "220",
            "W": "8",
            "Dc": "Bright World is currently the official distribution system of Philips. Please contact Bright World immediately for advice on using the most accurate Ecofit  20W T8 1m2  Philips LED tube light.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "4"
        },
        {
            "Id": "21",
            "Br": "Philips",
            "Cl": "Led Tube",
            "Name": "Led Tube Light Essential 16W Philips",
            "Price": "13.7",
            "I1": "pl-09",
            "V": "220",
            "W": "16",
            "Dc": "By applying many advanced achievements of science and technology developed in the Essential T5 16W G5 I APR LED tube, Philips has helped this product get a lot of outstanding advantages during use.",
            "Cm1": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "This product is not good",
            "Rate": "3"
        },
        {
            "Id": "22",
            "Br": "Panasonic",
            "Cl": "Led Tube",
            "Name": "Led Tube Light T8 22W Panasonic",
            "Price": "6.9",
            "I1": "pa-05",
            "V": "220",
            "W": "22",
            "Dc": "Panasonic LED T8 22W tube light is designed to light up with a lifespan of 15,000 hours, saving more than 80% of electrical energy consumption compared to traditional fluorescent lamps, which is a modern lighting solution.",
            "Cm1": "Shop carefully packed, good light, satisfied with the product",
            "Cm2": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm3": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Rate": "5"
        },
        {
            "Id": "23",
            "Br": "Panasonic",
            "Cl": "Led Tube",
            "Name": "Led Tube Light T8 18W Panasonic",
            "Price": "6",
            "I1": "pa-06",
            "V": "220",
            "W": "18",
            "Dc": "Panasonic T8 18W LED tube light has a long life of up to 15,000 hours with long-term use, saving electricity, providing a stable, quality light source in the electrical system when in use.",
            "Cm1": "Good light bulb, reasonable price",
            "Cm2": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm3": "Good product, well packaged, will buy again in the future",
            "Rate": "4"
        },
        {
            "Id": "24",
            "Br": "Panasonic",
            "Cl": "Led Tube",
            "Name": "Led Tube Light T8 9W Panasonic",
            "Price": "4.1",
            "I1": "pa-07",
            "V": "220",
            "W": "9",
            "Dc": "Panasonic LED T8 9W tube lights are manufactured using modern led chip technology according to modern Japanese production lines. Therefore, materials and designs are strictly and carefully selected to create quality and long-lasting lighting effects for the electrical system to use.",
            "Cm1": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "3"
        },
        {
            "Id": "25",
            "Br": "Comet",
            "Cl": "Led Tube",
            "Name": "Led Tube Light 1m2 18W Comet",
            "Price": "4.1",
            "I1": "co-07",
            "V": "100-265",
            "W": "18",
            "Dc": "Comet is a brand specializing in research, production and distribution of electrical equipment that has developed for a long time in the Vietnamese market. Referring to Comet, people often think of LED tube lights that are greatly upgraded compared to traditional product lines and can completely replace old electrical equipment. We would like to introduce to customers the 1m2 18W LED tube light product line Comet.",
            "Cm1": "This product is not good",
            "Cm2": "Shop carefully packed, good light, satisfied with the product",
            "Cm3": "Super fast and professional delivery. Genuine and very bright ball, good to use.",
            "Rate": "4"
        },
        {
            "Id": "26",
            "Br": "Comet",
            "Cl": "Led Tube",
            "Name": "Led Tube Light 0m6 9W Comet",
            "Price": "2.6",
            "I1": "co-08",
            "V": "100-265",
            "W": "9",
            "Dc": "Comet is one of the famous and familiar brands in Vietnam. Comet specializes in researching, manufacturing and distributing industrial and civil electrical products with diverse models, outstanding quality and efficiency. And among those led tube lights, it is impossible not to mention the LED tube light 0m6 9W",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good light bulb, reasonable price",
            "Cm3": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Rate": "5"
        },
        {
            "Id": "27",
            "Br": "Comet",
            "Cl": "Led Tube",
            "Name": "Led Tube Light 0m6 8W Comet",
            "Price": "1.8",
            "I1": "co-09",
            "V": "100-265",
            "W": "8",
            "Dc": "Comet 0m6 8W LED tube light is a product of the Comet company with effective lighting capabilities, helping consumers to be provided with the best light source without spending too much money thanks to its ability to save electricity.",
            "Cm1": "Good product, well packaged, will buy again in the future",
            "Cm2": "Good quality, fast delivery, easy to use",
            "Cm3": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Rate": "4"
        },
        {
            "Id": "28",
            "Br": "Paragon",
            "Cl": "Led Tube",
            "Name": "Led Tube Light 20W T8 Paragon",
            "Price": "6.1",
            "I1": "pr-05",
            "V": "220",
            "W": "20",
            "Dc": "Today, the use of energy-saving lighting solutions is something that many consumers are very interested in as energy costs continue to rise. Paragon 20W LED tube light has a lifespan of 50,000 hours, much higher than a traditional conventional fluorescent bulb.",
            "Cm1": "Shop carefully packed, good light, satisfied with the product",
            "Cm2": "This product is not good",
            "Cm3": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Rate": "3"
        },
        {
            "Id": "29",
            "Br": "Paragon",
            "Cl": "Led Tube",
            "Name": "Led Tube Light 10W T8 Paragon",
            "Price": "5",
            "I1": "pr-06",
            "V": "220",
            "W": "10",
            "Dc": "The Paragon 10W LED tube light product meets the lighting standards of European countries, providing a much better quality light source than traditional lamps and filament lamps. LED tube light is a lighting device that perfectly meets the light and aesthetics of any space, bringing high value to users.",
            "Cm1": "Super fast and professional delivery. Genuine and very bright ball, good to use.",
            "Cm2": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm3": "Good light bulb, reasonable price",
            "Rate": "4"
        },
        {
            "Id": "30",
            "Br": "Paragon",
            "Cl": "Led Tube",
            "Name": "Led Tube Light 40W T8 Paragon",
            "Price": "7.3",
            "I1": "pr-07",
            "V": "220",
            "W": "20",
            "Dc": "A product like the 20W Paragon led tube light is both high quality and environmentally friendly, while helping you save a significant amount of money every month. The special thing is that the 20W  Paragon led tube light product also protects the health of your loved ones in your family, giving customers the experience of outstanding features of the product line.",
            "Cm1": "Good quality, fast delivery, easy to use",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Rate": "4"
        },
        {
            "Id": "31",
            "Br": "RangDong",
            "Cl": "Led Decor",
            "Name": "Led String Light 100/8W Rang Dong",
            "Price": "14.5",
            "I1": "rd-16",
            "I2": "rd-17",
            "I3": "rd-18",
            "V": "220",
            "W": "8",
            "Dc": "Rang Dong 100/8W LED string light is a decorative light design manufactured by the manufacturer use a striking, more aesthetically pleasing lighting design for the consumer electrical system of decorative lighting. Rang Dong is introduced to the market with the aim of providing consumers with an outstanding lighting design. and more aesthetic for the electrical system. decorative lighting consumption.",
            "Cm1": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "This product is not good",
            "Rate": "3"
        },
        {
            "Id": "32",
            "Br": "RangDong",
            "Cl": "Led Decor",
            "Name": "Led String Lights 7W Rang Dong IP65",
            "Price": "2.5",
            "I1": "rd-19",
            "I2": "rd-20",
            "I3": "rd-21",
            "V": "220",
            "W": "7",
            "Dc": "7W LED string light Rang Dong IP65 is one of the LED string lights with a slim design, good flexibility, easier to install as well as saving time and effort of users. As a new product line, the lamp still ensures preeminent features to serve the decorative needs of users.",
            "Cm1": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm2": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "4"
        },
        {
            "Id": "33",
            "Br": "RangDong",
            "Cl": "Led Decor",
            "Name": "Led String Lights 9W Rang Dong IP65",
            "Price": "3",
            "I1": "rd-22",
            "I2": "rd-23",
            "I3": "rd-24",
            "V": "220",
            "W": "9",
            "Dc": "9W LED string light Rang Dong  is manufactured based on modern lines and extremely strict standards, so this lighting device not only possesses outstanding quality, but the durability of this led string light is also very high.",
            "Cm1": "Good light bulb, reasonable price",
            "Cm2": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm3": "Good product, well packaged, will buy again in the future",
            "Rate": "5"
        },
        {
            "Id": "34",
            "Br": "Philips",
            "Cl": "Led Decor",
            "Name": "Led String Lights 8W 50m Philips",
            "Price": "4.7",
            "I1": "pl-10",
            "I2": "pl-11",
            "V": "220-240",
            "W": "8",
            "Dc": "Led string light 6.8W 50m Philips is a product of Philips in the line of Led string lights. Products applying many science and technology along with modern and closed production lines create outstanding product quality. This is the best-selling product on the market of LED string lights, becoming the first choice of many customers.",
            "Cm1": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "3"
        },
        {
            "Id": "35",
            "Br": "Philips",
            "Cl": "Led Decor",
            "Name": "Led String Lights 18W 5m Philips",
            "Price": "8.3",
            "I1": "pl-12",
            "I2": "pl-13",
            "I3": "pl-14",
            "V": "220-240",
            "W": "18",
            "Dc": "Philips LED string light 18W 5m has a 5m-long wire design that is commonly used in quality lighting activities, maximizes decoration efficiency in the process of use, and minimizes a safe and stable light source. in the power system.",
            "Cm1": "This product is not good",
            "Cm2": "Shop carefully packed, good light, satisfied with the product",
            "Cm3": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Rate": "3"
        },
        {
            "Id": "36",
            "Br": "Philips",
            "Cl": "Led Decor",
            "Name": "Led String Lights 12.5W Philips",
            "Price": "30.4",
            "I1": "pl-15",
            "I2": "pl-16",
            "I3": "pl-17",
            "V": "220-240",
            "W": "12.5",
            "Dc": "12.5W LED string light Philips is one of the famous lights that are being chosen by many businesses and consumers as a product for their decorative lighting space. than. Therefore, we believe that this device will also bring customers certain benefits.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good light bulb, reasonable price",
            "Cm3": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Rate": "5"
        },
        {
            "Id": "37",
            "Br": "Panasonic",
            "Cl": "Led Decor",
            "Name": "Led String Lights 9W R/G/B Panasonic",
            "Price": "8.8",
            "I1": "pa-08",
            "I2": "pa-09",
            "I3": "pa-10",
            "V": "220-230",
            "W": "9",
            "Dc": "9W led string light NST120R/G/B Panasonic a lighting product that is optimally supported for choosing a safe light energy source, maximum protection of lighting operations with problems of uptime , usage choices and consumption demand for energy with positive use efficiency.",
            "Cm1": "Good product, well packaged, will buy again in the future",
            "Cm2": "Good quality, fast delivery, easy to use",
            "Cm3": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Rate": "4"
        },
        {
            "Id": "38",
            "Br": "Panasonic",
            "Cl": "Led Decor",
            "Name": "Led String Lights 6W Panasonic",
            "Price": "8.3",
            "I1": "pa-11",
            "I2": "pa-12",
            "I3": "pa-13",
            "V": "220-230",
            "W": "6",
            "Dc": "Panasonic NST1202/NST1206 6W led string lights are designed with flexible color changing capabilities and high economic efficiency with 6W providing a stable and long-lasting lighting energy source to maximize the long-term light source, save electricity.",
            "Cm1": "Shop carefully packed, good light, satisfied with the product",
            "Cm2": "This product is not good",
            "Cm3": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Rate": "3"
        },
        {
            "Id": "39",
            "Br": "Paragon",
            "Cl": "Led Decor",
            "Name": "Led String Lights 12W Paragon",
            "Price": "6.5",
            "I1": "pr-08",
            "I2": "pr-09",
            "V": "DC 24",
            "W": "12",
            "Dc": "Led string lights 12W Paragon a modern lighting product that maximizes the demand for electricity, saves bright space and lighting operation time through the need to choose high-end electrical equipment, need Use a high light source.",
            "Cm1": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm2": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm3": "Good light bulb, reasonable price",
            "Rate": "4"
        },
        {
            "Id": "40",
            "Br": "Paragon",
            "Cl": "Led Decor",
            "Name": "Led String Lights 14.4W RGB Paragon",
            "Price": "11.4",
            "I1": "pr-10",
            "I2": "pr-11",
            "V": "DC 24",
            "W": "14.4",
            "Dc": "14.4W LED5050/RGB Paragon led string light is known as an economical, long-lasting and stable lighting product for all your lighting needs, saving space, preserving space energy with flame retardant performance. long-term consumption results, making the most of safe, economical and highly aesthetic light sources.",
            "Cm1": "Good quality, fast delivery, easy to use",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Rate": "5"
        },
        {
            "Id": "41",
            "Br": "Paragon",
            "Cl": "Led Decor",
            "Name": "Led String Lights 14.4W Paragon",
            "Price": "7.6",
            "I1": "pr-12",
            "I2": "pr-13",
            "V": "DC 24",
            "W": "14.4",
            "Dc": "Led string lights 14.4W LED5050 Paragon with the main advantages of low energy consumption, negligible heat, long life, ensuring electrical safety, color flexibility, ultra-thin design, so led string lights are suitable used as decorative lights in small and narrow spaces to well preserve consumer needs.",
            "Cm1": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "This product is not good",
            "Rate": "3"
        },
        {
            "Id": "42",
            "Br": "RangDong",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 20W Rang Dong",
            "Price": "17",
            "I1": "rd-25",
            "V": "220",
            "W": "20",
            "Dc": "LED spotlight 20W Rang Dong is a new product line of Rang Dong with many modern features, luxurious and beautiful design and suitable for all different spaces.",
            "Cm1": "Very professional shop, reasonable prices. Fast and guaranteed delivery.",
            "Cm2": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "4"
        },
        {
            "Id": "43",
            "Br": "RangDong",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 12W Rang Dong",
            "Price": "22.5",
            "I1": "rd-26",
            "V": "220",
            "W": "12",
            "Dc": "Rang Dong has long been known as a reputable brand specializing in the production and distribution of high-end electrical equipment in the Vietnamese market. Rang Dong's products are always well received and trusted by consumers. 12W LED spotlight Rang Dong is also a device favored by many people thanks to its attractive features and optimal convenience.",
            "Cm1": "Good light bulb, reasonable price",
            "Cm2": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm3": "Good product, well packaged, will buy again in the future",
            "Rate": "4"
        },
        {
            "Id": "44",
            "Br": "RangDong",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 14W Rang Dong",
            "Price": "12.4",
            "I1": "rd-27",
            "V": "220",
            "W": "14",
            "Dc": "Rang Dong 14W LED spotlights provide a solution for spot lighting, lighting with quality Led light sources, reliability and long life when using LED spotlights.",
            "Cm1": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "4"
        },
        {
            "Id": "45",
            "Br": "Philips",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 8W Philips",
            "Price": "17.3",
            "I1": "pl-18",
            "I2": "pl-19",
            "V": "220",
            "W": "8",
            "Dc": "The Philips 8W LED spotlight is the result of practical application research from customers around the world today. Designed with a high, stable and efficient light source suitable for installation in many different lighting spaces.",
            "Cm1": "This product is not good",
            "Cm2": "Shop carefully packed, good light, satisfied with the product",
            "Cm3": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Rate": "3"
        },
        {
            "Id": "46",
            "Br": "Philips",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 14W Philips",
            "Price": "25",
            "I1": "pl-20",
            "V": "220",
            "W": "14",
            "Dc": "The 14W Philips led spotlight provides a point light source for the store system, exhibition space, creating an artistic and aesthetic lighting space to increase the prominence of products that need appropriate brightness.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good light bulb, reasonable price",
            "Cm3": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Rate": "5"
        },
        {
            "Id": "47",
            "Br": "Philips",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 35W Philips",
            "Price": "34.5",
            "I1": "pl-21",
            "V": "220",
            "W": "35",
            "Dc": "The birth of LED spotlights from the Philips brand can be said to bring a new breeze to our lives. With many years of experience in the research role and bringing prestigious products, suitable for each changing rhythm of life, LED spotlight products with different capacities have quickly conquered many customers. customer image and the 35W Philips led spotlight product is one of them.",
            "Cm1": "Good product, well packaged, will buy again in the future",
            "Cm2": "Good quality, fast delivery, easy to use",
            "Cm3": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Rate": "4"
        },
        {
            "Id": "48",
            "Br": "Paragon",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 20W Paragon",
            "Price": "24.6",
            "I1": "pr-14",
            "V": "100-240",
            "W": "20",
            "Dc": "LED spotlights are one of the most popular LED lights today. With sophisticated, compact design and outstanding quality, LED spotlights have become the optimal choice in lighting as well as decoration in today's interior space. Paragon brand has launched quality LED spotlights to meet the needs of all customers. In particular, the 20W Paragon spotlight led product is a typical example.",
            "Cm1": "Shop carefully packed, good light, satisfied with the product",
            "Cm2": "This product is not good",
            "Cm3": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Rate": "3"
        },
        {
            "Id": "49",
            "Br": "Paragon",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 13W Paragon",
            "Price": "62.5",
            "I1": "pr-15",
            "V": "100-240",
            "W": "13",
            "Dc": "The 13W Paragon led spotlight is an outstanding product of the spotlight line with outstanding advantages that help you get interesting utilities during use, ensuring the ability to bring long-term lighting energy. , long-term savings, stability in the power system.",
            "Cm1": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm2": "Very professional shop, reasonable prices. Fast and guaranteed delivery.",
            "Cm3": " Good light bulb, reasonable price",
            "Rate": "4"
        },
        {
            "Id": "50",
            "Br": "Paragon",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 6W Paragon",
            "Price": "21.7",
            "I1": "pr-16",
            "V": "100-240",
            "W": "6",
            "Dc": "Led spotlight 6W / 30/40/65 Paragon is a popular product line on the market today thanks to its outstanding features and advantages. We hope that you will get the most interesting utilities during use.",
            "Cm1": "Good quality, fast delivery, easy to use",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Rate": "5"
        },
        {
            "Id": "51",
            "Br": "Duhal",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 4x12W Duhal",
            "Price": "85.3",
            "I1": "du-01",
            "V": "220",
            "W": "4*12",
            "Dc": "Lighting equipment is an indispensable condition for a project whether small or large. Currently, many famous brands in turn launch high-end product lines to meet the needs of customers. And the 4x12W AIC led spotlight is the perfect choice for any space today.",
            "Cm1": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "This product is not good",
            "Rate": "3"
        },
        {
            "Id": "52",
            "Br": "Duhal",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 7W Duhal",
            "Price": "10.3",
            "I1": "du-02",
            "V": "220",
            "W": "7",
            "Dc": "The 7W DIB Duhal LED spotlight is a very popular line of spotlights used by everyone on the market today. With many advantages from exterior design to quality inside, the product has really become one of the most popular lamp lines in Vietnam, a worthy product for you to experience and feel. .",
            "Cm1": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm2": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "4"
        },
        {
            "Id": "53",
            "Br": "Duhal",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 8x12W Duhal",
            "Price": "164.6",
            "I1": "du-03",
            "V": "220",
            "W": "8*12",
            "Dc": "Currently, a series of high-end electrical products are launched by manufacturers in turn to attract and fully meet the needs of consumers. The LED spotlight 8x12W AIC is one of the completely new lighting devices, a product line that has brought great success to the Duhal brand and brought a lot of convenience to everyone.",
            "Cm1": "Good light bulb, reasonable price",
            "Cm2": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm3": "Good product, well packaged, will buy again in the future",
            "Rate": "4"
        },
        {
            "Id": "54",
            "Br": "Anfaco",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 7W Anfaco",
            "Price": "26.7",
            "I1": "an-01",
            "V": "85-265",
            "W": "7",
            "Dc": "Anfaco is one of the famous brands, a manufacturer with extensive experience in manufacturing electrical products and distributing them worldwide. There have been devices that have made a positive impression and won the trust of consumers. One of those products, it is impossible not to mention the LED spotlight 7W AFC Anfaco.",
            "Cm1": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "4"
        },
        {
            "Id": "55",
            "Br": "Anfaco",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 12W Anfaco",
            "Price": "38.3",
            "I1": "an-02",
            "V": "85-265",
            "W": "12",
            "Dc": "For the modern market, LED lights are one of the most sold electrical product lines with extremely large quantities and constantly increasing. This proves that consumer demand for lighting equipment is gradually increasing in both quantity and quality. LED spotlight 12W AFC 870 Anfaco is the product we want to introduce to customers today.",
            "Cm1": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm2": "This product is not good",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "3"
        },
        {
            "Id": "56",
            "Br": "Anfaco",
            "Cl": "Led Spotlight",
            "Name": "Led Spotlight 4W Anfaco",
            "Price": "8.16",
            "I1": "an-03",
            "V": "85-265",
            "W": "4",
            "Dc": "AFC Anfaco 4W LED spotlights are designed and manufactured accgnized standards. All materials used to make the product are imported from European countries, tested to ensure 100% safety.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm3": "Good light bulb, reasonable price",
            "Rate": "5"
        },
        {
            "Id": "57",
            "Br": "RangDong",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 100W Rang Dong",
            "Price": "87.5",
            "I1": "rd-28",
            "V": "150-250",
            "W": "100",
            "Dc": "Rang Dong is a reputable company in the production of lighting equipment. Led headlight 100W Rang Dong is the latest product of the company today.",
            "Cm1": "Good product, well packaged, will buy again in the future",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "4"
        },
        {
            "Id": "58",
            "Br": "RangDong",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 30W Rang Dong",
            "Price": "17.5",
            "I1": "rd-29",
            "V": "150-250",
            "W": "30",
            "Dc": "Deploying and manufacturing lighting products from Samsung Led chips, in the new product line of Rang Dong, the Led headlight 30W Rang Dong was born with a quality level of lighting and a guarantee of a long-lasting light source. Lighting equipment is indispensable in safe lighting activities, saving electricity with the best quality, serving consumer lighting.",
            "Cm1": "This product is not good",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "3"
        },
        {
            "Id": "59",
            "Br": "RangDong",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 40W Rang Dong",
            "Price": "20",
            "I1": "rd-30",
            "V": "150-250",
            "W": "40",
            "Dc": "A lighting product with many advantages will always attract consumers to choose to use. So customers should choose a 30W Rang Dong led headlight product that has good advantages to use.",
            "Cm1": "Good light bulb, reasonable price",
            "Cm2": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm3": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Rate": "4"
        },
        {
            "Id": "60",
            "Br": "Philips",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 20W Philips",
            "Price": "18",
            "I1": "pl-22",
            "V": "220",
            "W": "20",
            "Dc": "In modern life, electricity and electrical equipment always play an extremely important role, as one of the conditions for life and production and business activities. Understanding this, Philips has launched the Philips 20W LED floodlight product line - a new solution for modern and high-class living spaces.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "4"
        },
        {
            "Id": "61",
            "Br": "Philips",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 70W Philips",
            "Price": "75.8",
            "I1": "pl-23",
            "V": "220",
            "W": "70",
            "Dc": "You are in need of a large-capacity led headlight to serve outdoor lighting in the family premises. LED Headlight 70W LED 60/CW WB Philips will be a great product for your family.",
            "Cm1": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm3": "This product is not good",
            "Rate": "3"
        },
        {
            "Id": "62",
            "Br": "Philips",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 15W Philips",
            "Price": "15.2",
            "I1": "pl-24",
            "V": "220",
            "W": "15",
            "Dc": "Philips LED headlight 20W 17342 is one of the modern lights that apply lighting technology with high-end led chips. This is a popular technology and is often applied in high-end LED product lines to create maximum lighting efficiency.",
            "Cm1": "Shop carefully packed, good light, satisfied with the product",
            "Cm2": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm3": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Rate": "4"
        },
        {
            "Id": "63",
            "Br": "Panasonic",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 20W Panasonic",
            "Price": "12.5",
            "I1": "pa-14",
            "V": "220",
            "W": "20",
            "Dc": "Panasonic 20W LED headlight is one of the most popular lighting devices on the market today. With many advantages in both design and light quality, the product can fully support you effectively in your daily life and work.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Good light bulb, reasonable price",
            "Rate": "4"
        },
        {
            "Id": "64",
            "Br": "Panasonic",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 50W Panasonic",
            "Price": "27.9",
            "I1": "pa-15",
            "V": "220",
            "W": "50",
            "Dc": "In modern life, electricity gradually plays an important role and the demand for electrical products also gradually increases over time. Therefore, Panasonic 50W Led headlights were launched to the market to meet the needs of everyone.",
            "Cm1": "Good quality, fast delivery, easy to use",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm3": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Rate": "4"
        },
        {
            "Id": "65",
            "Br": "Panasonic",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 30W Panasonic",
            "Price": "18.3",
            "I1": "pa-16",
            "V": "220",
            "W": "30",
            "Dc": "The need to improve the quality of the lighting system is now a necessary need of everyone in order to create utilities and promote efficiency for the process of daily living, working and studying. Led headlight 30W, a product of the famous Panasonic brand, was born with the aim of serving the maximum for human life.",
            "Cm1": "This product is not good",
            "Cm2": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "3"
        },
        {
            "Id": "66",
            "Br": "Comet",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 10W Comet",
            "Price": "11.6",
            "I1": "co-10",
            "V": "100-240",
            "W": "10",
            "Dc": "Choosing a product such as 10W Comet Led floodlight is a problem for consumers because nowadays fake products are always flooding the market and only with the normal eyes of consumers, they will not distinguish them. ",
            "Cm1": "Good light bulb, reasonable price",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Rate": "4"
        },
        {
            "Id": "67",
            "Br": "Comet",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 20W Comet",
            "Price": "14.6",
            "I1": "co-11",
            "V": "100-240",
            "W": "20",
            "Dc": "20W Comet Led floodlight is a product used to illuminate the street system, residential area, garden ... with good lighting quality, safety.",
            "Cm1": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "4"
        },
        {
            "Id": "68",
            "Br": "Comet",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 30W Comet",
            "Price": "17.5",
            "I1": "co-12",
            "V": "100-240",
            "W": "30",
            "Dc": "30W Comet Led floodlight is an energy-saving, safe and stable lighting product in the consumer electrical system.",
            "Cm1": "Super fast and professional delivery. Genuine and very bright ball, good to use.",
            "Cm2": "This product is not good",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "3"
        },
        {
            "Id": "69",
            "Br": "Paragon",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 30W Paragon",
            "Price": "42.7",
            "I1": "pr-17",
            "V": "220",
            "W": "30",
            "Dc": "The 30W Paragon Led floodlight distributed by Bright World is an electrical device of good quality and outstanding lighting efficiency. This device is really the perfect choice for every home and every public building.",
            "Cm1": "Good light bulb, reasonable price",
            "Cm2": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm3": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Rate": "4"
        },
        {
            "Id": "70",
            "Br": "Paragon",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 20W Paragon",
            "Price": "74.8",
            "I1": "pr-18",
            "V": "220",
            "W": "20",
            "Dc": "What is the best solution for outdoor wall lighting today? The 20W Paragon Led Headlight deserves to be named only.",
            "Cm1": "Good quality, fast delivery, easy to use",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm3": "Good product, well packaged, will buy again in the future",
            "Rate": "4"
        },
        {
            "Id": "71",
            "Br": "Paragon",
            "Cl": "Led Outdoor",
            "Name": "Led Headlight 120W Paragon",
            "Price": "239.5",
            "I1": "pr-19",
            "V": "220",
            "W": "120",
            "Dc": "The waterproof 120W Paragon Led floodlight product possesses many outstanding advantages to be able to conquer all customers who choose it when using it. This LED headlight lighting device can guarantee to bring you a perfect lighting space and surprisingly economical.",
            "Cm1": "This product is not good",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "3"
        },
        {
            "Id": "72",
            "Br": "RangDong",
            "Cl": "Led Panel",
            "Name": "Led Panel 60x60 50W Rang Dong",
            "Price": "95",
            "I1": "rd-31",
            "V": "220",
            "W": "50",
            "Dc": "With many outstanding improvements compared to similar products, Rang Dong 60x60/50W Led panel light is manufactured by an advanced and current number one production line in Vietnam. Rang Dong's production team, through this line of led panel lights, wants to bring customers the best led panel light products, optimally supporting the lighting needs of consumers.",
            "Cm1": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm2": "Good light bulb, reasonable price",
            "Cm3": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Rate": "4"
        },
        {
            "Id": "73",
            "Br": "RangDong",
            "Cl": "Led Panel",
            "Name": "Led Panel 60x60 40W Rang Dong",
            "Price": "49.5",
            "I1": "rd-32",
            "V": "220",
            "W": "40",
            "Dc": "LED Panel Light P04 60x60/40W Rang Dong, a square plate product with a slim and compact design suitable for stable, safe and energy-saving lighting design when used, was launched and introduced by Rang Dong. to all customers.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "5"
        },
        {
            "Id": "74",
            "Br": "RangDong",
            "Cl": "Led Panel",
            "Name": "Led Panel 30x120 50W Rang Dong",
            "Price": "95",
            "I1": "rd-33",
            "V": "220",
            "W": "50",
            "Dc": "Led panel lights 30x120/50W Rang Dong are carefully checked at every stage from design to production before being put on the market in order to bring to customers the most perfect products, ensuring maximum service quality for customers. lighting needs of customers.",
            "Cm1": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm3": "This product is not good",
            "Rate": "3"
        },
        {
            "Id": "75",
            "Br": "Philips",
            "Cl": "Led Panel",
            "Name": "Led Panel 36W 600x600 Philips",
            "Price": "27",
            "I1": "pl-25",
            "V": "220-240",
            "W": "39",
            "Dc": "With the introduction of large panel led lights, high lighting needs will be served in the easiest way. To meet the requirements of even the most demanding customers, Philips has launched the 36W 600x600 Philips led panel light.",
            "Cm1": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm2": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "4"
        },
        {
            "Id": "76",
            "Br": "Philips",
            "Cl": "Led Panel",
            "Name": "Led Panel 29W Philips",
            "Price": "45.8",
            "I1": "pl-26",
            "V": "220-240",
            "W": "29",
            "Dc": "The 29W Philips led panel light not only has a modern design, perfect light quality, but also helps save energy as well as ensure safety for users.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Good light bulb, reasonable price",
            "Rate": "5"
        },
        {
            "Id": "77",
            "Br": "Philips",
            "Cl": "Led Panel",
            "Name": "Led Panel 30W CertaFlux 600x600 Philips",
            "Price": "36.7",
            "I1": "pl-27",
            "V": "220-240",
            "W": "30",
            "Dc": "Led panel light 44W CertaFlux 865/840 600x600 Philips is a Led Panel light product of the Philips brand - a brand that has received a lot of trust from consumers. Philips always focuses on developing more and more modern LED products to better meet the lighting needs of consumers. Led Panel light is a product line that is highly appreciated by consumers. The product brings high light efficiency, suitable for many different spaces.",
            "Cm1": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm2": "Good quality, fast delivery, easy to use",
            "Cm3": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Rate": "3"
        },
        {
            "Id": "78",
            "Br": "Paragon",
            "Cl": "Led Panel",
            "Name": "Led Panel 24W/30/42/65 Paragon",
            "Price": "40",
            "I1": "pr-20",
            "V": "220",
            "W": "24",
            "Dc": "Led panel light 24W 24L/30/42/65 Paragon will definitely become a product line representing a completely new lighting trend. This high-end lighting device from Paragon will surely become your effective assistant in upgrading your living and working space.",
            "Cm1": "Shop carefully packed, good light, satisfied with the product",
            "Cm2": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm3": "This product is not good",
            "Rate": "3"
        },
        {
            "Id": "79",
            "Br": "Paragon",
            "Cl": "Led Panel",
            "Name": "Led Panel 40W/30/42/65 Paragon",
            "Price": "70.8",
            "I1": "pr-21",
            "V": "220",
            "W": "40",
            "Dc": "For today's modern life, a comfortable living space will definitely bring work efficiency and satisfactory quality of life. Therefore, people need to improve their living and working space. Led panel light 40W/30/42/65 Paragon – a new lighting solution for modern life, promising to be a great assistant for you.",
            "Cm1": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm2": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm3": "Good light bulb, reasonable price",
            "Rate": "4"
        },
        {
            "Id": "80",
            "Br": "Paragon",
            "Cl": "Led Panel",
            "Name": "Led Panel 20W/30/42/65 Paragon",
            "Price": "32.2",
            "I1": "pr-22",
            "V": "220",
            "W": "20",
            "Dc": "Led panel light 20W 30/42/65 Paragon is one of the product lines that you can easily see in large commercial centers, interior showrooms... This is a high-end product line of the brand. Paragon is famous and currently very popular with many people.",
            "Cm1": " Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "5"
        },
        {
            "Id": "81",
            "Br": "Duhal",
            "Cl": "Led Panel",
            "Name": "Led Panel 40W DGA204 Duhal",
            "Price": "90",
            "I1": "du-04",
            "V": "220",
            "W": "40",
            "Dc": "Led panel light 40W Duhal is designed in a square, rectangular shape, the surface of the lamp is quite thin and produces a light source with a large amplification. The product is gradually being noticed by consumers today and has become quite popular in Vietnam.",
            "Cm1": "Shop carefully packed, good light, satisfied with the product",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "This product is not good",
            "Rate": "3"
        },
        {
            "Id": "82",
            "Br": "Duhal",
            "Cl": "Led Panel",
            "Name": "Led Panel 20W DGA802M Duhal",
            "Price": "19.1",
            "I1": "du-05",
            "V": "220",
            "W": "20",
            "Dc": "After a stressful working day, home is the most private and comfortable space when returning home. Because of that, many people are very strict in the design and selection of products for their own space. And LED panel light 20W Duhal is the first choice of the majority of consumers on the market today.",
            "Cm1": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm2": "Good light bulb, reasonable price",
            "Cm3": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Rate": "4"
        },
        {
            "Id": "83",
            "Br": "Duhal",
            "Cl": "Led Panel",
            "Name": "Led Panel 40W DGA804 Duhal",
            "Price": "42.4",
            "I1": "du-06",
            "V": "220",
            "W": "40",
            "Dc": "Led panel light 40W Duhal is manufactured according to modern technology and equipped with high-class Led chip for a light source that meets European standards and ensures safety for users' health.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "5"
        },
        {
            "Id": "84",
            "Br": "RangDong",
            "Cl": "Led Street",
            "Name": " Led Street Light 120W Rang Dong",
            "Price": "335",
            "I1": "rd-34",
            "V": "150-270",
            "W": "120",
            "Dc": "Led street light 120W Rang Dong is currently a product used to illuminate the roads in big cities today.",
            "Cm1": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm2": "This product is not good",
            "Cm3": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Rate": "3"
        },
        {
            "Id": "85",
            "Br": "RangDong",
            "Cl": "Led Street",
            "Name": " Led Street Light 150W Rang Dong",
            "Price": "238",
            "I1": "rd-35",
            "V": "150-270",
            "W": "150",
            "Dc": "A 150W Rang Dong Led street light product with many advantages in operation will be the product that customers trust and choose to use the most.",
            "Cm1": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm2": "Shop carefully packed, good light, satisfied with the product",
            "Cm3": "Very professional shop, reasonable prices. Fast and guaranteed delivery.",
            "Rate": "4"
        },
        {
            "Id": "86",
            "Br": "RangDong",
            "Cl": "Led Street",
            "Name": " Led Street Light 200W Rang Dong",
            "Price": "229",
            "I1": "rd-36",
            "V": "150-270",
            "W": "200",
            "Dc": "To evaluate the durability of the LED street light 200W Rang Dong, consumers must base on the advantages that the product owns.",
            "Cm1": "Good light bulb, reasonable price",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Rate": "4"
        },
        {
            "Id": "87",
            "Br": "Philips",
            "Cl": "Led Street",
            "Name": "Led Street Light 200W Philips",
            "Price": "208.3",
            "I1": "pl-28",
            "V": "220",
            "W": "200",
            "Dc": "200W Philips LED street light is designed and manufactured according to advanced and modern technology lines of developed countries to ensure a quality, safe and energy-saving light source, is the perfect lighting solution. for a variety of spaces from street lighting to foyer lighting, parks, squares, etc.",
            "Cm1": "Good quality, fast delivery, easy to use",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Rate": "4"
        },
        {
            "Id": "88",
            "Br": "Philips",
            "Cl": "Led Street",
            "Name": "Led Street Light 36W Philips",
            "Price": "216.7",
            "I1": "pl-29",
            "V": "220",
            "W": "36",
            "Dc": "The 36W Philips led street light is designed and manufactured with high quality materials and advanced LED technology, committed to providing an efficient light source, meeting European standards. The bulb has high luminescence efficiency and reasonable illuminance, providing soft and glare-free light to ensure safety for everyone on the road.",
            "Cm1": "This product is not good",
            "Cm2": "Shop carefully packed, good light, satisfied with the product",
            "Cm3": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Rate": "3"
        },
        {
            "Id": "89",
            "Br": "Philips",
            "Cl": "Led Street",
            "Name": "Led Street Light 149W Philips",
            "Price": "258.3",
            "I1": "pl-30",
            "V": "220",
            "W": "149",
            "Dc": "In order to contribute to creating an image of urban beauty, a modern, safe and clean green city, the lighting system is very important. Therefore, most urban planners are looking for modern lighting devices that not only meet the lighting needs, but also are effective and economical economic solutions. And the 149W Philips led street light is the perfect choice.",
            "Cm1": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm2": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm3": "Good light bulb, reasonable price",
            "Rate": "4"
        },
        {
            "Id": "90",
            "Br": "Paragon",
            "Cl": "Led Street",
            "Name": "Led Street Light 180W Paragon",
            "Price": "496",
            "I1": "pr-23",
            "V": "100-240",
            "W": "180",
            "Dc": "The 180W Paragon Led street light has brought significant changes to social life because the lamp possesses many outstanding advantages.",
            "Cm1": "Good quality, fast delivery, easy to use",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm3": "Good product, well packaged, will buy again in the future",
            "Rate": "5"
        },
        {
            "Id": "91",
            "Br": "Paragon",
            "Cl": "Led Street",
            "Name": "Led Street Light 100W Paragon",
            "Price": "216.7",
            "I1": "pr-24",
            "V": "100-240",
            "W": "100",
            "Dc": "100W Paragon Led Street Light is an efficient and sustainable lighting quality device, saving energy, reducing power consumption by up to 70% compared to traditional lighting systems with much higher quality light. .",
            "Cm1": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm2": "This product is not good",
            "Cm3": "Shop carefully packed, good light, satisfied with the product",
            "Rate": "3"
        },
        {
            "Id": "92",
            "Br": "Paragon",
            "Cl": "Led Street",
            "Name": "Led Street Light 160W Paragon",
            "Price": "288",
            "I1": "pr-25",
            "V": "100-240",
            "W": "160",
            "Dc": "The 160W Paragon led street light is a high-power lamp that is used exclusively for outdoor lighting such as streets, highways, highways, parks, football fields, etc. .",
            "Cm1": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Cm2": "Good light bulb, reasonable price",
            "Cm3": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Rate": "4"
        },
        {
            "Id": "93",
            "Br": "Duhal",
            "Cl": "Led Street",
            "Name": "Led Street Lights 90W SHDS90 Duhal",
            "Price": "167.8",
            "I1": "du-07",
            "V": "220",
            "W": "90",
            "Dc": "Led street light 90W SHDS90 Duhal is used to illuminate the outside space where people often travel such as national highways, bridges, etc. This device is used to provide light for pedestrians when it is dark.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good product, well packaged, will buy again in the future",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "4"
        },
        {
            "Id": "94",
            "Br": "Duhal",
            "Cl": "Led Street",
            "Name": "Led Street Lights 90W SLDS90 Duhal",
            "Price": "210.8",
            "I1": "du-08",
            "V": "220",
            "W": "90",
            "Dc": "Led street light 90W SLDS90 Duha is a lighting device with a long life, good lighting quality, does not emit harmful ultraviolet rays or ultraviolet rays that affect people and the surrounding environment, ensuring quality of life. Live a better, more modern life.",
            "Cm1": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm2": "Very quality products, fast delivery, good service, will continue to support for a long time.",
            "Cm3": "This product is not good",
            "Rate": "3"
        },
        {
            "Id": "95",
            "Br": "Duhal",
            "Cl": "Led Street",
            "Name": "Led Street Lights 250W HDD250 Duhal",
            "Price": "68.8",
            "I1": "du-09",
            "V": "220",
            "W": "250",
            "Dc": "Led street light 250W HDD250 Duhal is a great choice thanks to its superior features such as long service life, high lighting efficiency, environmental friendliness and remarkable power saving ability.",
            "Cm1": "Shop carefully packed, good light, satisfied with the product",
            "Cm2": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm3": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Rate": "4"
        },
        {
            "Id": "96",
            "Br": "Anfaco",
            "Cl": "Led Street",
            "Name": "Led Street Lights DDB 100W Anfaco",
            "Price": "166.7",
            "I1": "an-04",
            "V": "85-265",
            "W": "100",
            "Dc": "Anfaco 100W DDB led street light can be said to be an indispensable product in our life, as well as in our lighting system construction activities today. Because when using lights, it will bring safety and save energy effectively, contributing to improving the quality of life.",
            "Cm1": "Fast delivery,the product is exactly as described correct delivery, carefully packaged",
            "Cm2": "Good light bulb, reasonable price",
            "Cm3": "Good product, well packaged, will buy again in the future",
            "Rate": "5"
        },
        {
            "Id": "97",
            "Br": "Anfaco",
            "Cl": "Led Street",
            "Name": "Led Street Lights DDB 50W Anfaco",
            "Price": "145.8",
            "I1": "an-05",
            "V": "85-265",
            "W": "50",
            "Dc": "We can choose the solution of using DDB 50W Anfaco led street lights instead because the product has the outstanding advantage of saving power up to 75% compared to incandescent high pressure lamps.",
            "Cm1": "Very quality products, fast delivery, good service, will continue to support for a long time",
            "Cm2": "Fast delivery, carefully packaged, very good lamp quality, light color is not dazzling",
            "Cm3": "Good quality, fast delivery, easy to use",
            "Rate": "4"
        },
        {
            "Id": "98",
            "Br": "Anfaco",
            "Cl": "Led Street",
            "Name": "Led Street Lights DDB 150W Anfaco",
            "Price": "208.3",
            "I1": "an-06",
            "V": "85-265",
            "W": "150",
            "Dc": "As the best lighting solution today, DDB 150W Anfaco led street light is considered as a lighting device with many outstanding advantages, so it is increasingly widely used in all areas of life in general and in the field of lighting. street lighting in particular.",
            "Cm1": "This product is not good",
            "Cm2": "Super fast and professional delivery. Genuine and very bright ball, good to use",
            "Cm3": "Very professional shop, reasonable prices. Fast and guaranteed delivery",
            "Rate": "3"
        }
    ]